// Generated by CoffeeScript 1.10.0
var EnemyHandler, enemies, enemyList;

enemies = null;

enemyList = [];

EnemyHandler = (function() {
  function EnemyHandler() {
    enemies = game.add.group();
    enemies.enableBody = true;
  }

  EnemyHandler.prototype.spawn = function(x, y) {
    var enemy;
    enemy = new Enemy(x, y, 'enemy');
    enemies.add(enemy.ref);
    enemyList.push(enemy);
  };

  return EnemyHandler;

})();
