// Generated by CoffeeScript 1.10.0
var EnemyHandler, enemies;

enemies = null;

EnemyHandler = (function() {
  function EnemyHandler() {
    var enemy;
    enemies = game.add.group();
    enemies.enableBody = true;
    enemy = new Enemy(100, GameResolution.height / 2, 'enemy');
    enemies.add(enemy.ref);
  }

  return EnemyHandler;

})();
