// Generated by CoffeeScript 1.10.0
var EnemyManager, enemies, enemyList;

enemies = null;

enemyList = [];

EnemyManager = (function() {
  function EnemyManager() {
    enemies = game.add.group();
    enemies.enableBody = true;
  }

  EnemyManager.prototype.spawn = function(x, y) {
    var enemy;
    enemy = new Enemy(x, y, 'enemy');
    enemies.add(enemy.ref);
    enemyList.push(enemy);
  };

  return EnemyManager;

})();
