// Generated by CoffeeScript 1.10.0
var EnemyManager, enemies, enemyList;

enemies = null;

enemyList = [];

EnemyManager = (function() {
  EnemyManager.prototype.enemyOnScreen = false;

  function EnemyManager() {
    enemies = game.add.group();
    enemies.enableBody = true;
  }

  EnemyManager.prototype.spawn = function(x, y) {
    var enemy;
    this.enemyOnScreen = true;
    enemy = new Enemy(x, y, 'enemy');
    enemies.add(enemy.ref);
    return enemyList.push(enemy);
  };

  EnemyManager.prototype.spawnLoop = function() {
    var i, j, results;
    if (!this.enemyOnScreen) {
      results = [];
      for (i = j = 1; j <= 1; i = ++j) {
        results.push(this.spawn(player.ref.x + i * 200, GameWorld.groundHeight));
      }
      return results;
    }
  };

  return EnemyManager;

})();
