// Generated by CoffeeScript 1.10.0
var GameplayState, healthManager, player;

player = null;

healthManager = null;

GameplayState = {
  preload: function() {},
  load: function() {},
  create: function() {
    var enemyManager;
    game.world.setBounds(0, 0, GameWorld.width, GameWorld.height);
    game.physics.startSystem(Phaser.Physics.ARCADE);
    levelInit();
    healthManager = new HealthManager();
    player = new Player(300, GameResolution.height / 2, 'player');
    game.camera.follow(player.ref, Phaser.Camera.FOLLOW_PLATFORMER);
    enemyManager = new EnemyManager();
    enemyManager.spawn(100, GameResolution.height / 2);
    inputInit();
    scoreInit();
  },
  update: function() {
    var enemy, i, j, len, len1;
    game.physics.arcade.collide(player.ref, platforms);
    game.physics.arcade.collide(enemies, platforms);
    for (i = 0, len = enemyList.length; i < len; i++) {
      enemy = enemyList[i];
      game.physics.arcade.overlap(player.ref, enemy.bullets, player.hit, null, this);
      game.physics.arcade.overlap(enemy.ref, player.bullets, enemy.hit, null, this);
    }
    keyboardMovement();
    buttonMovement();
    for (j = 0, len1 = enemyList.length; j < len1; j++) {
      enemy = enemyList[j];
      enemy.AI();
    }
  }
};
