// Generated by CoffeeScript 1.10.0
var HealthManager;

HealthManager = (function() {
  HealthManager.prototype.heartScale = 0.08;

  function HealthManager() {
    var heart, i, j, ref;
    this.hearts = game.add.group();
    for (i = j = 1, ref = player.health; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      heart = this.hearts.create(GameResolution.width - 60 * i, 15, 'heart');
      heart.scale.setTo(this.heartScale, this.heartScale);
      heart.fixedToCamera = true;
    }
  }

  HealthManager.prototype.loseHealth = function() {
    player.health--;
    if (player.health > 0) {
      return this.hearts.children[player.health].destroy();
    } else {
      return game.state.start('Menu');
    }
  };

  return HealthManager;

})();
