// Generated by CoffeeScript 1.10.0
var HealthManager;

HealthManager = (function() {
  HealthManager.prototype.hearts = null;

  HealthManager.prototype.currentHealth = 3;

  function HealthManager() {
    var heart, i, j;
    this.hearts = game.add.group();
    for (i = j = 1; j <= 3; i = ++j) {
      heart = this.hearts.create(GameResolution.width - 60 * i, 15, 'heart');
      heart.scale.setTo(0.08, 0.08);
      heart.fixedToCamera = true;
    }
  }

  HealthManager.prototype.loseHealth = function() {
    if (this.currentHealth > 0) {
      this.hearts.children[this.currentHealth - 1].destroy();
      this.currentHealth--;
    }
  };

  return HealthManager;

})();
