// Generated by CoffeeScript 1.10.0
var inputInit, keyboard, shootKey, spacebar;

keyboard = null;

spacebar = null;

shootKey = null;

inputInit = function() {
  keyboard = game.input.keyboard.createCursorKeys();
  spacebar = game.input.keyboard.addKey(Phaser.Keyboard.SPACEBAR);
};
