// Generated by CoffeeScript 1.10.0
var inputInit, keyboard, spacebar;

keyboard = null;

spacebar = null;

inputInit = function() {
  var jump, left, right, shoot;
  keyboard = game.input.keyboard.createCursorKeys();
  spacebar = game.input.keyboard.addKey(Phaser.Keyboard.SPACEBAR);
  left = game.add.sprite(0, game.world.height - 320, 'button_left');
  right = game.add.sprite(160, game.world.height - 320, 'button_right');
  jump = game.add.sprite(320, game.world.height - 320, 'button_jump');
  shoot = game.add.sprite(480, game.world.height - 320, 'button_shoot');
};
