// Generated by CoffeeScript 1.10.0
var GameWorld, levels;

GameWorld = {
  height: GameResolution.height,
  width: 2000,
  groundHeight: 608,
  l1: 470,
  l2: 350,
  l3: 230
};

levels = [];

levels[0] = [];

levels[1] = [[-150, GameWorld.l2], [300, GameWorld.l1], [750, GameWorld.l2], [1200, GameWorld.l3], [1200, GameWorld.l1], [1650, GameWorld.l2]];

levels[2] = [];

levels[3] = [];
