// Generated by CoffeeScript 1.10.0
var GameResolution, create, game, main, preload, update;

GameResolution = {
  width: 800,
  height: 600
};

game = null;

main = function() {
  return game = new Phaser.Game(GameResolution.width, GameResolution.height, Phaser.AUTO, '', {
    preload: preload,
    create: create,
    update: update
  });
};

preload = function() {
  game.load.image('sky', 'img/sky.png');
  game.load.image('ground', 'img/platform.png');
  game.load.image('star', 'img/star.png');
  game.load.spritesheet('dude', 'img/dude.png', 32, 48);
};

create = function() {
  game.add.sprite(0, 0, 'star');
};

update = function() {};
