// Generated by CoffeeScript 1.10.0
var MenuState;

MenuState = {
  preload: function() {},
  load: function() {},
  create: function() {
    var text;
    game.add.sprite(0, 0, 'background');
    this.playButton = new Phaser.Button(game, 128, 416, 'button_general', this.playPressed, this, 0, 0, 1, 0);
    this.playButton.tint = 0xE74C3C;
    game.add.existing(this.playButton);
    text = game.add.text(this.playButton.x + this.playButton.width / 2, this.playButton.y + this.playButton.height / 2, 'Play', {
      font: '48px invasion2000',
      fill: 'white',
      align: 'center'
    });
    return text.anchor.set(0.5);
  },
  update: function() {},
  playPressed: function() {
    return game.state.start('Gameplay');
  }
};
