// Generated by CoffeeScript 1.10.0
var Player, bullets;

bullets = null;

Player = (function() {
  Player.prototype.movementSpeed = 200;

  Player.prototype.jumpSpeed = 300;

  Player.prototype.bulletSpeed = 300;

  Player.prototype.playerScale = 2;

  Player.prototype.facing = "right";

  Player.prototype.fireRate = 3;

  Player.prototype.lastFired = 0;

  Player.prototype.ref = null;

  function Player() {
    this.ref = game.add.sprite(32, GameResolution.height / 2, 'player');
    this.ref.scale.setTo(this.playerScale, this.playerScale);
    this.ref.smoothed = false;
    this.ref.anchor.setTo(.5, 1);
    this.ref.frame = 6;
    game.camera.follow(this.ref, Phaser.Camera.FOLLOW_PLATFORMER);
    game.physics.arcade.enable(this.ref);
    this.ref.body.gravity.y = 300;
    this.ref.body.collideWorldBounds = true;
    bullets = game.add.group();
    bullets.enableBody = true;
    this.ref.animations.add('walking', [0, 1, 2, 3, 4, 5], 12, true);
    this.ref.animations.add('jumping', [6, 7, 8, 9], 12, true);
  }

  Player.prototype.moveLeft = function() {
    this.facing = "left";
    this.ref.body.velocity.x = -this.movementSpeed;
    if (this.ref.body.touching.down) {
      this.ref.animations.play('walking');
    }
    if (this.ref.scale.x > 0) {
      this.ref.scale.x *= -1;
    }
  };

  Player.prototype.moveRight = function() {
    this.facing = "right";
    this.ref.body.velocity.x = this.movementSpeed;
    if (this.ref.body.touching.down) {
      this.ref.animations.play('walking');
    }
    if (this.ref.scale.x < 0) {
      this.ref.scale.x *= -1;
    }
  };

  Player.prototype.jump = function() {
    this.ref.body.velocity.y = -this.jumpSpeed;
    this.ref.animations.play('jumping');
  };

  Player.prototype.idle = function() {
    this.ref.animations.stop();
    this.ref.frame = 6;
  };

  Player.prototype.shoot = function() {
    var projectile, projectileVector;
    this.lastFired = game.time.now;
    if (this.facing === "right") {
      projectile = bullets.create(this.ref.x + 30, this.ref.y - 48, 'bullet');
      projectileVector = this.bulletSpeed;
    } else {
      projectile = bullets.create(this.ref.x - 40, this.ref.y - 48, 'bullet');
      projectileVector = -this.bulletSpeed;
    }
    projectile.scale.setTo(2, 2);
    projectile.body.velocity.x = projectileVector;
    projectile.checkWorldBounds = true;
    projectile.outOfBoundsKill = true;
  };

  return Player;

})();
