// Generated by CoffeeScript 1.10.0
var ScoreManager;

ScoreManager = (function() {
  ScoreManager.prototype.score = 0;

  ScoreManager.prototype.scoreText = null;

  function ScoreManager() {
    this.scoreText = game.add.text(16, 4, 'Score: 0', {
      font: '32px invasion2000',
      fill: '#fff'
    });
    this.scoreText.fixedToCamera = true;
  }

  ScoreManager.prototype.increment = function(amount) {
    this.score += amount;
    this.scoreText.text = 'Score: ' + this.score;
  };

  return ScoreManager;

})();
