// Generated by CoffeeScript 1.10.0
var score, scoreInit, scoreText;

score = 0;

scoreText = null;

scoreInit = function() {
  return scoreText = game.add.text(16, 16, 'Score: 0', {
    fontSize: '32px',
    fill: '#fff'
  });
};
